### ISSUE TITLE
Expose documentation of plot_utils

### ISSUE THREAD

**Issue by fsaad** [probcomp/bdbcontrib#114]
`__init__.py` redefines the API functions `plot_utils` to return those functions, rather than import them directly. The results is clobbering the documentation.

```
In [22]: bdbcontrib.pairplot?
Signature: bdbcontrib.pairplot(*args, **kwargs)
Docstring: <no docstring>
File:      ~/bdbcontrib/bdbcontrib/__init__.py
Type:      function
```

**Comment by gregory-marton** [comment]
Actively working on it.

**Comment by riastradh-probcomp** [comment]
FYI, the reason I did that was to prevent `import bdbcontrib.anything` from having the effect of loading `bdbcontrib.plot_utils` which took forever because of seaborn/matplotlib/fontconfig/something, without changing the semantics of `import bdbcontrib` in that first change.  I intended to convert all callers to just use `bdbcontrib.plot_utils` and get rid of anything from just plain `import bdbcontrib`, but of course like everyone I'm short on round tuits.  So in order to fix this I would suggest just doing that last step.

**Comment by riastradh-probcomp** [comment]
Also, if you do `from import bdbcontrib.plot_utils import pair_plot`, you get the docstring.  So there's no problem for callers who specify what part of bdbcontrib they're trying to use, which was the whole intent behind the bdbcontrib agglomeration anyway.

**Comment by gregory-marton** [comment]
My plan is to use helpsub from [py_utils](https://github.com/probcomp/bdbcontrib/blob/master/src/py_utils.py), and at to advertise them through the quickstart interface.

**Comment by riastradh-probcomp** [comment]
Why not just remove them?  Simpler, clearer.
