### ISSUE TITLE
Feature request: allow bdbcontrib.heatmap to accept 2d DataFrames

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/bdbcontrib#136]
Seaborn clustermap accepts 2d square DataFrames, so it is intuitive that bdbcontrib.heatmap should also be able to do it. 

Implementation suggestion - 
In bdbcontrib.plot_utils, line 800, change
```
    else:
        complete_df = ensure_full_square(data_df, clustermap_kws['pivot_kws'])
        hmap = sns.clustermap(complete_df, **clustermap_kws)
```
by
```
    else:
        if not is_full_square(data_df):
                complete_df = ensure_full_square(data_df, clustermap_kws['pivot_kws'])
        else:
                complete_df = data_df
        hmap = sns.clustermap(complete_df, **clustermap_kws)
```
where ```is_full_square``` is a function for checking whether a df is full square.

**Comment by gregory-marton** [comment]
That's a misunderstanding of `ensure_full_square`, which ensures that all of the pairs involved in a full square appear in the paired matrix, rather than actually creating a square matrix. 

In fact, any matrix might be appropriate to heatmap, not only square ones. Heatmap has the pivot_kws option because it's not easy to tell whether something is "any matrix" or one of these lists-of-pairs matrices automatically. In this case, you're asking to be able to tell sns.heatmap that it does not need to pivot at all. 

If there were a BQL query that resulted in a heatmap like that, that also is not the kind of thing `pairplot` is meant to show, then I would say that yes, we want to do this. Can you think of one?

If not, then I'd rather leave this functionality to seaborn, letting people call seaborn.heatmap directly if they wish. Closing for now, but please re-open if you have a sample BQL query that this should show.
