### ISSUE TITLE
Indexing error in barplot when not plotting two columns

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bdbcontrib#31]
From @vkmvkmvkmvkm:
> Needed to ask Feras about why obscure indexing error in barplot was happening. Answer was I needed 2 columns from SELECT output (which makes perfect sense in hindsight). Also iterating was difficult --- needed to ask Taylor about the bdb.savepoint() business b/c of annoying "table already exists"... --- and finally, can't collapse into single SIMULATE due to surface syntax limitations (this should be signposted in an error with a TBD: properly re-embed SQL)

"_ = bdbcontrib.barplot(satellites_bdb, '''
SIMULATE purpose FROM satellites_cc
GIVEN country_of_operator = ""China (PR)"" 
LIMIT 1000;
''')"
"<...> /Volumes/BayesDB/BayesDB-bayes0.1rc1-1-gd96fe22.app/Contents/MacOS/venv/lib/python2.7/site-packages/matplotlib/backends/backend_agg.pyc in __init__(self, width, height, dpi)
     92         self.height = height
     93         if __debug__: verbose.report('RendererAgg.__init__ width=%s, height=%s'%(width, height), 'debug-annoying')
---> 94         self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
     95         self._filter_renderers = []
     96 

ValueError: width and height must each be below 32768
"

**Comment by gregory-marton** [comment]
Fixed in e169454.

The error is better, but the top part is still misleading. That's a general problem with how we report errors in ipynbs though, not something specific to this issue.
<img width="1102" alt="screen shot 2016-02-05 at 10 23 18 pm" src="https://cloud.githubusercontent.com/assets/5065456/12864390/3507ee38-cc57-11e5-926d-7611277d2b11.png">
