### ISSUE TITLE
Save BQL and SQL traces and infrastructure to send on port

### ISSUE THREAD

**Issue by marcoct** [probcomp/bdbcontrib#46]
@tibbetts began this on this branch: [20150910-tibbetts-sessions](https://github.com/probcomp/bayeslite/compare/20150910-tibbetts-sessions). Currently sessions are being stored into the database in table "bayesdb_session_entries".

Steps:
1. bdbcontrib function for printing all of the sessions to screen.
2. modify function to send out on port
3. server running on csail to accept it

**Comment by marcoct** [comment]
As of [this bdbcontrib commit](https://github.com/probcomp/bdbcontrib/commit/0fd774654b47758d651f283c471bb4dc223062e5) and [this bayeslite commit](https://github.com/probcomp/bayeslite/commit/3ad5529180c9f75f0cb20dae112f3d9cf9dd7251), sessions are now being stored in the table, and can be explored and dumped to JSON with the following:

from bdbcontrib import bql_utils
bql_utils.dump_current_session_as_json(bdb)
bql_utils.current_session_id(bdb)
bql_utils.dump_session_as_json(bdb, session_id)

**Comment by marcoct** [comment]
Next steps are:
1. Decide on when sessions should get sent. @tibbetts: Do we want to send messages on termination of every session, on-demand with a bdbcontrib function call, and/or on crash or other event?
2. Decide on how we will be sending sessions.
3. Implement piece to send
4. Implement server to receive.

**Comment by marcoct** [comment]
Also, should this session data be encrypted? Some users may need this.

**Comment by marcoct** [comment]
Also, should the bayeslite shell also include this functionality?

**Comment by marcoct** [comment]
Should detect crash or bad termination and suggest send trace on next open.
Should suggest on backtrace or error when we improve error messages. Same for on seatbelt hit or timeout.

**Comment by marcoct** [comment]
Detecting of crash is now implemented by adding a completed column to the bayesdb_session_entries table. The completed field is initially false for each entry, and is only set to true after the results of the query are available. 

For (bql) execute, a crash or exception during the following calls will result in a command listed as not completed:
```
        phrases = parse.parse_bql_string(string)
        phrase = None
        try:
            phrase = phrases.next()
        except StopIteration:
            raise ValueError('no BQL phrase in string')
        try:
            phrases.next()
        except StopIteration:
            pass
        else:
            raise ValueError('>1 phrase in string')
        cursor = bql.execute_phrase(self, phrase, bindings)
```

For (bql) execute, a crash or exception during the following call will result in a command listed as not completed:
```
        cursor = self.sqlite3.execute(string, bindings)
```

Upon re-opening, if session saving is enabled, the previous session is checked for any uncompleted entries. If there are any, this message is printed:
```
WARNING: Previous session contains uncompleted entries. This may be due to a bad termination or crash of the previous session. Consider uploading the session.
```

**Comment by marcoct** [comment]
bdbcontrib functions for clearing session history, pausing and restarting session logging, and viewing basic session information, are now implemented.

**Comment by marcoct** [comment]
Next step is sending the session data. I have a shell for this in bdbcontrib:
```
def send_session_data(bdb, session_id):
    """Send all saved session history."""
    session_id = current_session_id(bdb)
    for id in range(1, session_id+1):
        json_string = dump_session_as_json(bdb, id)
        # TODO send it
```
Will sync with @gregory-marton to get pointers about sending this over SSL to a server running on csail.

**Comment by marcoct** [comment]
Notes from grem:
.cgi
- use python cgi library on the server side
- use urllib2 post on the client (bdbcontrib site)

- TIG CSAIL error logs
- CGI error logs
http://tig.csail.mit.edu/wiki/TIG/WebServerLogs

**Comment by marcoct** [comment]
JSON dumps of sessions is now implemented:

- server side: https://github.com/probcomp/probcomp-website/commit/dfd09a52e886ff30b438dee96c6ca78191eabd03
- client (bdbcontrib): https://github.com/probcomp/bdbcontrib/commit/83be755762c1a91d5fdd8324324e88e437f8fb61

**Comment by riastradh-probcomp** [comment]
Date: Wed, 30 Sep 2015 08:56:15 -0700
   From: Marco Cusumano-Towner <notifications@github.com>

   Notes from grem:
   .cgi
   - use python cgi library on the server side
   - use urllib2 post on the client (bdbcontrib site)

FYI: The current way that we do HTTP requests, in bayesdb-demo and in
the module in bayeslite that phones home to snoop on what versions
users are running, is to use the Python `requests' module, not urllib.

I have not made a technical assessment of the differences between the
two, but I figure if we're going to do essentially the same thing in
different ways there should be a documented reason for it.

**Comment by riastradh-probcomp** [comment]
Date: Tue, 29 Sep 2015 19:33:58 -0700
   From: Marco Cusumano-Towner <notifications@github.com>

   Will sync with @gregory-marton to get pointers about sending this
   over SSL to a server running on csail.

Using SSL is (a) needless technical complexity (b) needless
administrative headache and (c) needless opportunities for back doors
without (d) lots of work to invent our own ad-hoc version of
certificate pinning like Google used to detect Iran's compromise of
DigiNotar to MITM Gmail users three years ago.

All we need is a single public key which we can embed in the source
code, just like we do with bayesdb-demo, but in this case for
encryption rather than signature.  I can elaborate on this next week.

**Comment by riastradh-probcomp** [comment]
Date: Tue, 29 Sep 2015 14:31:16 -0700
   From: Marco Cusumano-Towner <notifications@github.com>

   Should detect crash or bad termination and suggest send trace on next open.
   Should suggest on backtrace or error when we improve error messages. Same for on seatbelt hit or timeout.

I maintain that such things should be part of a user interface using
semantically sensible APIs, e.g. a progress hook just like sqlite3
has, which *in*a*user*interface* (such as the bayeslite shell) could
be set to test a timeout or check for some notion of a crash.  Such
things don't make sense in a useful library API.

**Comment by riastradh-probcomp** [comment]
Date: Tue, 29 Sep 2015 14:21:02 -0700
   From: Marco Cusumano-Towner <notifications@github.com>

   Also, should this session data be encrypted? Some users may need this.

It is not simply that `some users may need this'.  This is a basic,
fundamental responsibility of any agent using the internet; to do
otherwise in any new protocols is negligent.

**Comment by marcoct** [comment]
I refactored the changes to the BayesDB class to remove session saving items, leaving only the generic tracing methods that were there previously. Now, session saving is explicitly turned on (as an instance of a tracer) by the user with:
```
bdb = ...
session_tracer = bayeslite.sessions.SessionTracer(bdb)
```
The user can then stop and start session-saving, clear sessions, dump session data to JSON, and optionally send their session data to probcomp with the command:
```
session_tracer.send_session_data()
```
This is implemented in bayeslite in src/sessions.py: https://github.com/probcomp/bayeslite/commit/5bf7063188cfb7c3287330b927922fcbbb10d837 
I can move this to bdbcontrib, but currently table that records the sessions is defined as part of the bayeslite schema. The table definitions and the class that uses them it should probably be placed in the same place. I deleted my earlier branch on bdbcontrib as this functionality is now part of bayeslite/src/sessions.py.

I also created an unit test as part of bayeslite for this (test_sessions.py). The testing of sending session data is currently disabled.

I have not yet addressed the security concerns.

**Comment by tibbetts** [comment]
Thanks Marco, appreciate the factoring, and don't yet have an answer for how to think about schema. Might be another instance of the bdbcontrib/bayeslite split being artificial, or a need for schema extensions (smells like overkill, unless it is also what alternate gpms use), or just that things like session capture which add new artifacts to the database should be in core. Let's ask ourselves if we must answer this question now or can we be agile about it in some way.

For libraries, I agree let's use requests instead of urllib/urllib2/httplib2, for consistency and because as I recall it is easier to use, more friendly to modern web things, and is better maintained. http://docs.python-requests.org/en/latest/community/faq/#why-not-httplib2

Regarding security concerns, I think not using SSL is also irresponsible, because it means disclosure of our private key or compromise of our homebrew system exposes all previously transmitted user data, not just users who were being targeted by sophisticated bad actors at the time of transmission (if I remember the Iran/Google/SSL case correctly, I didn't look it up). One option would be to public key encrypt and also SSL the connections.

However, I think the best answer is not to public key encrypt at all, because it sets the wrong expectation for what is going to happen to this data. I need students and researchers to be able to look at this data and analyze it and derive things from it. I don't want to take encrypted data and then store it in MIT AFS cleartext, or store it encrypted by be permiscuous in sharing the decryption key. I don't want to have to encrypt or secure every derived representation of the data. I think the key thing is to set user expectations of privacy on this data low, and make sure we are not violating expectations or trust when we, e.g., publish papers containing aggregates or partially anonymized information from these traces.

I agree that a better UI, and UI level specialization of these interactions, would be better. I disagree strongly that the command line shell is any part of the solution. In the near future, we should look for ways to make the best possible interface, probably via improvements to iPython notebooks like a custom kernel. For now, the only expected use of bayeslite is via python notebooks. Third party use of bayeslite as an embedded library is not the common case, is primarily done by our close collaborators, and can even be harder if it has to be to achieve the research goal of end users working interactively with the tool.

My recommendations are to make minimal change to the security code, mostly fix what library we are using and make sure we aren't screwing up in any obvious way (I haven't actually reviewed the code). And to make sure that documentation and notifications make it clear to users that their data will be used for research purposes.

**Comment by riastradh-probcomp** [comment]
Date: Sat, 03 Oct 2015 11:44:39 -0700
   From: Richard Tibbetts <notifications@github.com>

   Thanks Marco, appreciate the factoring, and don't yet have an
   answer for how to think about schema. Might be another instance of
   the bdbcontrib/bayeslite split being artificial, or a need for
   schema extensions (smells like overkill, unless it is also what
   alternate gpms use), or just that things like session capture which
   add new artifacts to the database should be in core. Let's ask
   ourselves if we must answer this question now or can we be agile
   about it in some way.

I don't recall exactly what the question about schema was, but there's
nothing wrong with bdbcontrib modules installing their own tables as
long as they're clearly set apart from the standard BayesDB tables.
E.g., naming them all bayesdb_session_* should be OK.

   I don't want to have to encrypt or secure every derived
   representation of the data. I think the key thing is to set user
   expectations of privacy on this data low, and make sure we are not
   violating expectations or trust when we, e.g., publish papers
   containing aggregates or partially anonymized information from
   these traces.

In that case, it must be very clearly an opt-in system, and to
emphasize the fact I think we ought to publish all the data we receive
immediately, so that our responsibility for handling users' data
securely does not fundamentally rely on the users' ISPs and local
networks to do the same.

   For now, the only expected use of bayeslite is via python
   notebooks. Third party use of bayeslite as an embedded library is
   not the common case, is primarily done by our close collaborators,
   and can even be harder if it has to be to achieve the research goal
   of end users working interactively with the tool.

Making the whole system be a giant front end was one of the main
problems with the maintainability of the old BayesDB code base.  I
think it would be a mistake to integrate user interface bells and
whistles into the library even if we have only one primary intended
mode of interaction.

**Comment by riastradh-probcomp** [comment]
Date: Sat, 3 Oct 2015 21:56:42 +0000
   From: Taylor R Campbell <riastradh+probcomp@csail.mit.edu>

      Date: Sat, 03 Oct 2015 11:44:39 -0700
      From: Richard Tibbetts <notifications@github.com>

      I don't want to have to encrypt or secure every derived
      representation of the data. I think the key thing is to set user
      expectations of privacy on this data low, and make sure we are not
      violating expectations or trust when we, e.g., publish papers
      containing aggregates or partially anonymized information from
      these traces.

   In that case, it must be very clearly an opt-in system, and to
   emphasize the fact I think we ought to publish all the data we receive
   immediately, so that our responsibility for handling users' data
   securely does not fundamentally rely on the users' ISPs and local
   networks to do the same.

To clarify that point a little: if we want to do anything less than
full publication of the data we send, we ought to encrypt it over the
wire so that we have a chance to decide after it has been sent how
much to publish.

I am not suggesting that we promise users security guarantees, and
encrypting data over the wire does not imply such a promise.  It is
only a basic responsibility if we are not a priori sure that we want
full publication.


On opt-in/opt-out: I am pretty sure that I don't personally want to
get in the business of handling data sets collected from users who did
not explicitly consent to giving them to me.  As you mentioned,
securing the stored data sets is another problem -- as is, e.g., even
copying them anywhere at all if users claim copyright on them.

**Comment by gregory-marton** [comment]
Example notebooks now feature text prominently inviting people into the community.
New projects are very clearly opt-in.

I disagree that full immediate publication of data we receive is a necessity. In fact, doing so might expose our users to timing attacks that they otherwise might not need to worry about, independent of the contents of their datasets or queries.

Data in transmission post to an https url. Data at rest are acl'd in AFS. We have not passed a security audit, and I think it would be a mistake in priorities to attempt to do so. We have done due diligence.
